default:
  logger: &logger
    name: webot
    #level 'CRITICAL','ERROR','WARNING','INFO','DEBUG'

development:
  logger:
    <<: *logger
    file_log:
      filename: debug_log.log
      level: DEBUG
    stdout_log:
      level: DEBUG
  selenium:
    type: remote
    #remote_server_path: http://192.168.33.1:4444/wd/hub
    remote_server_path: http://127.0.0.1:4444/wd/hub
    #proxy_host: 36.238.87.236
    #proxy_port: 3128
  mongo:
    database: selepy_development
    proscraper_database: proscraper_development
    host: 127.0.0.1
    port: 27017
