from abstract_name_generator import AbstractNameGenerator
from chinese_name_generator import ChineseNameGenerator
from english_name_generator import EnglishNameGenerator
from japanese_name_generator import JapaneseNameGenerator
from korean_name_generator import KoreanNameGenerator
